AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ApplicationDomain:
    Description: Application domain
    Type: String

Conditions:
  IsProd: !Equals [!Ref ApplicationDomain, prod.admin.bluestone.dev]

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - 'X-Requested-With'
              - 'content-type'
              - 'Authorization'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: 3600

  DeployBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeployBucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Resource: !Join ["", [!GetAtt DeployBucket.Arn, "/*"]]

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !If [IsProd, [!Ref ApplicationDomain, "admin.bluestone.dev"], [!Ref ApplicationDomain]]
        CustomErrorResponses:
          - ErrorCachingMinTTL: 86400
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 0
          TargetOriginId: !Ref DeployBucket
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Name: CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Name: CORS-S3Origin
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd # Name: CORS-With-Preflight
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt DeployBucket.DomainName
            Id: !Ref DeployBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        PriceClass: PriceClass_All
        ViewerCertificate:
          # Use hardcoded arn for now. Need to change to create certificate for each domain
          # when we can validate the certificate automatically using DNS.
          # AcmCertificateArn: !Ref Certificate
          AcmCertificateArn: "arn:aws:acm:us-east-1:730335240314:certificate/64923945-baf3-4ca7-901e-db9777b6d695"
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "CloudFront access to S3 bucket for ${ApplicationDomain}"

#  Certificate:
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: !Ref ApplicationDomain
#      ValidationMethod: DNS

  DomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      # Use hardcoded hosted zone id for now. It's pointing to bluestone.dev hosted zone.
      HostedZoneId: Z0335665EIV9VU3WPZ07
      Name: !Ref ApplicationDomain
      Type: A

  RootDomainRecord:
    Condition: IsProd
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      # Use hardcoded hosted zone id for now. It's pointing to bluestone.dev hosted zone.
      HostedZoneId: Z0335665EIV9VU3WPZ07
      Name: admin.bluestone.dev
      Type: A
